# Generated by Django 4.2.7 on 2025-08-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00ffff', help_text='Color en hex (ej: #00ffff)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del ícono', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('official_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('platform', models.CharField(choices=[('hackthebox', 'HackTheBox'), ('tryhackme', 'TryHackMe'), ('vulnhub', 'VulnHub'), ('ctftime', 'CTFTime'), ('picoctf', 'PicoCTF'), ('overthewire', 'OverTheWire'), ('custom', 'Custom Lab')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], max_length=10)),
                ('machine_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('machine_url', models.URLField(blank=True)),
                ('summary', models.TextField(help_text='Resumen corto del writeup')),
                ('content', models.TextField(help_text='Contenido completo en Markdown')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='writeups/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('reading_time', models.IntegerField(default=5, help_text='Tiempo estimado de lectura en minutos')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='writeups.category')),
                ('tags', models.ManyToManyField(blank=True, to='writeups.tag')),
            ],
            options={
                'verbose_name': 'WriteUp',
                'verbose_name_plural': 'WriteUps',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='writeups/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='writeups.writeup')),
            ],
            options={
                'verbose_name': 'Imagen de WriteUp',
                'verbose_name_plural': 'Imágenes de WriteUps',
            },
        ),
    ]
